name = "hono-cfw-auth"
main = "src/app.ts"
compatibility_date = "2024-12-14"
keep_vars = true

compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 3000

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 0 * * *"]